name: Release

# on:
#   push:
#     branches: [ main ]

on:
  push:
    branches-ignore: [ main ]

env:
  GITHUB_TOKEN: ${{ github.token }}
  SVU_VERSION: 1.10.2

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest

    outputs:
      VERSION: ${{ steps.tag.outputs.test }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: get-tags 
        run: git fetch --force --tags

      - name: Get svu
        run: |
          URL="https://github.com/caarlos0/svu/releases/download/v{SVU_VERSION}/svu_{SVU_VERSION}_linux_amd64.tar.gz"
          wget $URL -O svu_{SVU_VERSION}_linux_amd64.tar.gz
          tar -xzf svu.tar.gz
          chmod +x svu
          sudo mv svu /usr/local/bin/

      - id: tag
        run: |
          echo "VERSION=world" >> $GITHUB_OUTPUT
          git tag "$(svu next)"
          git push --tags

               

  goreleaser:
    needs: [tag]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v4
        with:
          check-latest: true    
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: ${{ needs.tag.outputs.VERSION }}
          args: release --clean --snapshot --skip-publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: verify
        run: ls -l dist/ && cat dist/artifacts.json | jq