name: Test & Validate

on:
  pull_request:
    types: ['synchronize', 'opened', 'reopened', 'ready_for_review']
    branches:
    - main

env:
  GITHUB_TOKEN: ${{ github.token }}
  MENDABLE_API_KEY: ${{secrets.MENDABLE_API_KEY}}
  SLACK_SIGNING_SECRET: ${{secrets.SLACK_SIGNING_SECRET}}


concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    if: ${{ !github.event.pull_request.draft }}
    steps:
    # If the condition above is not met, aka, the PR is not in draft status, then this step is skipped.
    # Because this step is part of the critical path, omission of this step will result in remaining CI steps not gettinge executed.
    # As of 8/8/2022 there is now way to enforce this beahvior in GitHub Actions CI.
      - run: exit 0


  linting:
    needs: [run-ci]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        check-latest: true

    - name: Lint Internal Package
      uses: golangci/golangci-lint-action@v3
      with:
        args: --verbose --timeout 5m

  test:
    name: Test
    needs: [run-ci,linting]
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        check-latest: true
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Go Tests
      run: |
        go test ./...

  compile:
    name: Compile validation
    needs: [run-ci,linting]
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        check-latest: true
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:  
        args: -v
  
    - name: build & execute
      run: |
        make start
        go build -ldflags="-X 'spectrocloud.com/spectromate/cmd.VersionString=1.0.0'" -o=spectromate -v

  Docker:
    needs: [run-ci,linting,test,compile]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        check-latest: true

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2


    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/${{ github.repository }}:dev
        build-args: |
          VERSION=1.0.0